# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: gh-impact-data
# email: iandennismiller@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  <b>gh-impact</b> is a measure of influence on GitHub.
baseurl: "/gh-impact" # the subpath of your site, e.g. /blog
url: "http://iandennismiller.github.io" # the base hostname & protocol for your site
twitter_username: iandennismiller
# github_username:  iandennismiller
include: ["_html"]
exclude: ["Readme.md", "Makefile", "vendor", "Gemfile", "Gemfile.lock"]
permalink: none

# Build settings
markdown: kramdown
